async function getName(){ //async를 함수이름 앞에 넣으면 항상 프로미스를 반환
  return "Mike";
}

console.log(getName());

async function getName(){
  throw new Error("error..");
}

getName().catch((err)=>{
  console.log(err);
})

//await : async내부에서만 사용가능

function getName(name){
  return new Promise((resolve,reject)=> {
    setTimeout((){
      resolve(name);
    },1000);
  });
}

async function showName(){
  const result = await getName("Mike");
  console.log(result);
}

console.log("시작");
showName();


async function order(){
  try{
    const result = await Promise.all([f1(),f2(),f3()]);
    console.log(result);
}catch(e){
    console.log(e);
  }
  console.log("종료");
}
order();



















